#!/usr/bin/env node
/* ==========================================================================
   build.js — bundles everything (HTML + CSS + JS) into one standalone file.

       node build.js

   Produces dist/wa-chat-viewer.html: a single file with no dependencies that
   opens with a double-click and works offline. Handy to copy onto a USB
   stick, send to someone, or keep next to your exports.
   ========================================================================== */
'use strict';

const fs = require('fs');
const path = require('path');

const root = __dirname;
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

let html = read('index.html');

// <link rel="stylesheet" href="..."> -> <style>…</style>
html = html.replace(/[ \t]*<link rel="stylesheet" href="([^"]+)">\n?/g, (_, href) =>
  '<style>\n' + read(href).trim() + '\n</style>\n');

// <script src="..."></script> -> <script>…</script>
html = html.replace(/[ \t]*<script src="([^"]+)"><\/script>\n?/g, (_, src) =>
  '<script>\n' + read(src).trim() + '\n</script>\n');

const banner = '<!--\n  WA Chat Viewer — a WhatsApp export viewer, all in one file.\n' +
               '  Generated by build.js on ' + new Date().toISOString().slice(0, 10) + '.\n' +
               '  No data leaves your device: the archive is read entirely in your browser.\n-->\n';
html = html.replace('<!doctype html>', '<!doctype html>\n' + banner);

fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
const out = path.join(root, 'dist', 'wa-chat-viewer.html');
fs.writeFileSync(out, html);

// only check real tag attributes, not strings inside the JS
const left = html.match(/<(?:link|script|img|source)\b[^>]*\b(?:href|src)="(?!data:|https?:|#)[^"]+"/g);
if (left) console.warn('Heads up — external references left behind:', left.join(', '));
console.log('Wrote ' + path.relative(root, out) + '  (' + (html.length / 1024).toFixed(0) + ' kB)');
